name: Cross-compile with Deno 2 and add to release

on:
  workflow_dispatch:
    inputs:
      RELEASETAG:
        description: "Release tag"
        required: true
        type: string
  release:
    types: [published]

jobs:
  build:
    name: "Compile for platform ${{matrix.target}} and add to release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    strategy:
      matrix:
        target:
          [
            "linux-x64",
            "linux-arm64",
            "macos-x64",
            "macos-arm64",
            "windows-x64",
          ]
    steps:
      - name: Determine tag to use
        run: |
          if [ -n "${{ inputs.RELEASETAG }}" ]; then
            echo "TAGTOUSE=${{ inputs.RELEASETAG }}" >> $GITHUB_ENV
            echo "Using manual tag ${{ inputs.RELEASETAG }}"
          else
            echo "TAGTOUSE=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "Using release tag ${{ github.ref_name }}"
          fi

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TAGTOUSE }}

      - name: Set up Deno (v2)
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Install dependancies
        run: deno install

      - name: Compile for ${{ matrix.target }}
        run: deno run compile:${{ matrix.target}}

      - name: Upload to GitHub Release
        run: |
          echo "Uploading artifacts to release: ${{ env.TAGTOUSE }}"
          file="lr-${{matrix.target}}"
          zipfile="$file.zip"
          zip -r "$zipfile" "$file"
          echo "Uploading '$zipfile' to release tag '${{ env.TAGTOUSE }}' ..."
          gh release upload "${{ env.TAGTOUSE }}" "$zipfile" --clobber
