name: Cross-compile with Deno 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            "linux-x64",
            "linux-arm64",
            "macos-x64",
            "macos-arm64",
            "windows-x64",
          ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Deno (v2)
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Install dependancies
        run: deno install

      - name: Compile for ${{ matrix.target }}
        run: deno run compile:${{ matrix.target}}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lr-${{ matrix.target }}
          path: dist
